### ISSUE TITLE
statsd-prom-bridge crashloobbackoff

### ISSUE THREAD

**Issue by Pamir** [henrybell/advanced-kubernetes-bootcamp#46]
Hi 
I have tried to install clusters based in dm-setup. I am attaching the istio-system pods and output of statsd

pamir_erdem@advanced-kubernetes-215013:~ kubectl get pods -n istio-system
NAME                                       READY     STATUS             RESTARTS   AGE
istio-citadel-7bdc7775c7-zpv7n             1/1       Running            0          5h
istio-egressgateway-795fc9b47-g6jtj        1/1       Running            0          5h
istio-ingress-84659cf44c-mkpxl             1/1       Running            0          5h
istio-ingressgateway-7d89dbf85f-xxf7q      1/1       Running            0          5h
istio-pilot-66f4dd866c-fxnmh               2/2       Running            0          5h
istio-policy-76c8896799-j7mwn              2/2       Running            0          5h
istio-sidecar-injector-645c89bc64-mlczt    1/1       Running            0          5h
istio-statsd-prom-bridge-949999c4c-2kt2d   0/1       CrashLoopBackOff   66         5h
istio-telemetry-6554768879-qlbsn           2/2       Running            0          5h
prometheus-86cb6dd77c-vrtqs                1/1       Running            0          5h
pamir_erdem@advanced-kubernetes-215013:~$ kubectl logs -n istio-system istio-statsd-prom-bridge-949999c4c-2kt2d
**statsd_exporter: error: unknown short flag '-s', try --help**

**Comment by Pamir** [comment]
Hi
I think we have to add two dashes  instead of one to istio-statsd-prom-bridge deployment. That fixes the crashloobbackoff error and pod starts without error message.

spec:
      containers:
      - args:
        - --statsd.mapping-config=/etc/statsd/mapping.conf
        image: prom/statsd-exporter:latest

**Comment by henrybell** [comment]
Hi Pamir -- thanks for this! We're shortly going to move to Istio 1.0.2, in which this should no longer be an issue:
https://github.com/istio/istio/issues/8293
