### ISSUE TITLE
Project settings for the cluster deployment

### ISSUE THREAD

**Issue by varungbt** [henrybell/advanced-kubernetes-bootcamp#47]
From the readme I understand that the dm-setup folder's code ensures Google Deployment Manager running in one project deploys GCP resources in another project.

Something that I could not catch hold of is 
1) How do you set the target project details where the cluster would need to get deployed  ?

**Comment by henrybell** [comment]
Hi -- this lab is intended to be run in a single GCP project. When we use this repository it's typically deployed into a project in the [Qwiklabs](https://qwiklabs.com) environment, but there's no reason why it shouldn't work in any project. Note that by default you may hit quota issues when deploying.
